#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "hi" one time
i=1
while [ $i -le 10 ]
do
  if [ $i -eq 9 ]
  then
      echo "Best School"
      echo "hi"
  else
      echo "Best School"
  fi
  ((i++))
done
